[build]
    command = "hugo"
    publish = "public"
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.80.0"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

      
[[redirects]]
  from = "/data/uptime.json"
  to = "https://netlify-uptime-json-bucket.s3.amazonaws.com/netlify/data/uptime.json"
  status = 200
  force = true

